### ISSUE TITLE
Students to check the participant tutorials

### ISSUE THREAD

**Issue by WanjaSchaible** [stella-project/stella-micro-template#5]
- [ ] Jüri, Ziyad, Julian and other students to check the [STELLA-micro-template](https://github.com/stella-project/stella-micro-template) for participants. Check [Issue 4](https://github.com/stella-project/stella-micro-template/issues/4)

**Comment by ziyad121** [comment]
I tested the micro-template  and everything works fine 
In the template that explains how to integrate ranker, there were some changes to do before everything ran :

1st problem:  recommender class is called in app.py but not defined in systems.py 
2nd problem:  Had to change random.choices to random.sample as the first one doesn't work.7

Other than that all tests are done without a problem.
